---
- name: Install package
  hosts: all
  become: yes
  tasks:
  - name: install package
    yum:
      name: falcon-sensor
      state: latest
      disable_gpg_check: yes
  - name: post install command
    command: /opt/CrowdStrike/falconctl -s --cid=7EECAC9F71C04D1F8F7826EEA5ABA14E-54 -f
    register: cmd_out
  - name: cmd_out
    debug:
      msg: '{{ cmd_out }}'
  - name: Restart service falcon-sensor, in all cases
    service:
     name: falcon-sensor
     state: restarted
     enabled: yes
